### ISSUE TITLE
Error when building project

### ISSUE THREAD

**Issue by ffesseler** [lecram/rover#12]
```
~/K/T/rover (master) $ make
cc  -o rover rover.c -lncursesw
rover.c:238:15: error: use of undeclared identifier 'SIGWINCH'
    sigaction(SIGWINCH, &sa, NULL);
              ^
rover.c:248:15: error: use of undeclared identifier 'SIGWINCH'
    sigaction(SIGWINCH, &sa, NULL);
              ^
rover.c:310:24: error: use of undeclared identifier 'SIGWINCH'
        kill(getpid(), SIGWINCH);
                       ^
3 errors generated.
make: *** [rover] Error 1
~/K/T/rover (master) $
```

```
~/K/T/rover (master) $ clang -v
Apple LLVM version 7.0.0 (clang-700.0.72)
Target: x86_64-apple-darwin15.0.0
Thread model: posix
```

**Comment by lecram** [comment]
See this: http://tin-dev.tin.narkive.com/cTikf6Nh/fwd-tin-fails-to-handle-sigwinch
What version of ncurses do you have installed?

**Comment by ffesseler** [comment]
How do I know what version I've installed ? :)

**Comment by ffesseler** [comment]
How do I know what version I've installed ? :)

**Comment by yggdr** [comment]
Hi, getting the same error on FreeBSD 10.1, ncurses is version 5.9.20150214_2

**Comment by lecram** [comment]
@ffesseler Try the command `ncursesw5-config --version`. You might need to replace the number 5 with some other number or remove it.

@yggdr Thanks for the info!

Can you guys test if it's working now? Commit 6a758e6a80e0a875dff32357a77fd2b3292aca1a should fix this.

**Comment by yggdr** [comment]
Works for me, thank you :)

**Comment by ffesseler** [comment]
So my version is 5.4.
Here is the output now that I've pulled the last changes :
```
cc  -o rover rover.c -lncursesw
ld: library not found for -lncursesw
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [rover] Error 1
```

**Comment by lecram** [comment]
That means the linker could not find ncurses' wide-character library. You'll need to check whether it's installed and see how it's named on your system. When you have that information, just edit the first line of the Makefile accordingly. The first thing I'd try is removing the `w` on the end.

**Comment by ffesseler** [comment]
yep, works fine now ! Thx !
