### ISSUE TITLE
Should attempt to use well-known pagers by default

### ISSUE THREAD

**Issue by mlawren** [lecram/rover#13]
Nearly all other unix commands I know will at least try to find a pager when $PAGER is not set, and since I usually only have one installed I have never needed to set it.

p.s. Cool tool!

**Comment by lecram** [comment]
Thanks for the feedback.

I don't want to give privilege to some programs by hardcoding their names in the source. That would open a bad precedent. $PAGER is a neutral, simple, widely used solution.

That said, if you always use the same pager, you can easily hardcode it yourself (see example patch below). One reason I try to keep to sources small is to allow such kind of customizing.

```diff
diff --git a/rover.c b/rover.c
index bc192f2..8efd800 100644
--- a/rover.c
+++ b/rover.c
@@ -1057,7 +1057,7 @@ main(int argc, char *argv[])
             }
         } else if (!strcmp(key, RVK_VIEW)) {
             if (!rover.nfiles || S_ISDIR(EMODE(ESEL))) continue;
-            program = getenv("PAGER");
+            program = "mypager";
             if (program) {
                 ARGS[0] = program;
                 ARGS[1] = ENAME(ESEL);
```
