### ISSUE TITLE
Option to show hidden files by default

### ISSUE THREAD

**Issue by Ypnose** [lecram/rover#23]
Hi there,
As the title says it, it could be very nice to add an option to show hidden files by default. :beer:

**Comment by lecram** [comment]
Commit 418661c adds this option to config.h. The default default was kept: you'll have to change your config to something like `#define RV_FLAGS SHOW_FILES | SHOW_DIRS | SHOW_HIDDEN` in order to show hidden files by default.

**Comment by Ypnose** [comment]
Thank you for the quick commit!
