### ISSUE TITLE
Open $SHELL on the currect directory and problems with recursive instances

### ISSUE THREAD

**Issue by dschrempf** [lecram/rover#25]
Hello,

is there a way to enter $SHELL on the current directory and quit rover?

What usually happens to me:
1. I use rover and enter $SHELL on a directory.
2. Do something there, forget that I was using rover.
3. Start another instance of rover, and so on.

Instead I should type exit to get back to the original rover instance.  However, maybe I also changed directory in the meantime and want to use this new directory as a starting point for using rover?

I also had problems with rover not responding because there were too many recursive instances.  Maybe I am just missing something fundamental, so please correct me.

**Comment by feute** [comment]
There's no way (at least not a sane one) to change the current directory of another process; in this case, the parent process. 

As you may notice, **rover** spawns a new shell every time you press `Return`, and that process uses the *new* current directory. `chdir(2)` only changes the current working directory of the process, that means, rover's process; it won't persist if you exit rover.

Can you please provide details about the recursive instances? How is it not responding? Maybe I'm not the right one to help you out in that part, but you could provide details so others can do it. :)

**Comment by lecram** [comment]
Hi @dschrempf.

Just to add to what @feute said: the closest you can get to what you want is [this FAQ entry](https://github.com/lecram/rover/blob/master/FAQ.md#how-to-use-rover-to-change-the-current-directory-of-a-shell).

I couldn't reproduce the bug mentioned. If it's still happening, feel free to open a new issue with more details.

**Comment by dschrempf** [comment]
Hi, thank you for the link to the FAQ entry. I also had no issues with a non-respnsive rover in the meantime.
