### ISSUE TITLE
Public Domain Dedication/License?

### ISSUE THREAD

**Issue by whereswaldon** [lecram/rover#33]
Would you be willing to license this code under a formal dedication to the public domain like [the unlicense](https://unlicense.org/) or [CC0](https://creativecommons.org/publicdomain/zero/1.0/)? I greatly respect that you've placed this code in the public domain, but these more verbose licenses ensure that your intentions are respected in countries that don't legally recognize the concept of "public domain." For a more thorough breakdown of why these licenses are helpful, see [this wiki article](https://en.wikipedia.org/wiki/Public_domain_equivalent_license).

**Comment by lecram** [comment]
Hi, @whereswaldon.
Personally I dislike these formal legal codes and am skeptical about their practical value or effectiveness.
If anyone is having legal obstacles trying to use any code from my repositories, I'd like to know the issue in detail.
