### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [lecram/rover#7]
Would you like to add more error handling for return values from functions like the following?
- [malloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [ls](https://github.com/lecram/rover/blob/9fa8b0aa5acbe5a67f362b4ef495c9ad5bffbe39/rover.c#L436)
- [sigaction](http://pubs.opengroup.org/onlinepubs/9699919799/functions/sigaction.html "Change a signal action.") ⇒ [enable_handlers](https://github.com/lecram/rover/blob/9fa8b0aa5acbe5a67f362b4ef495c9ad5bffbe39/rover.c#L227)

**Comment by lecram** [comment]
What problem would it solve?

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Unchecked return values") a bit more.

Are you interested to apply [aspect-oriented software development](http://aspectc.org/ "AspectC++")?
How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](http://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in your software?

**Comment by lecram** [comment]
Checking the returned value only makes sense if you want to take different actions depending on that value. I don't see how this is the case here. This program cannot fix the abnormal hypothetical conditions under which those functions fail.

**Comment by elfring** [comment]
How do you think about to indicate such failures by [a corresponding return code](https://en.wikipedia.org/wiki/Exit_status "Description for the exit status")?
