### ISSUE TITLE
Unicode support

### ISSUE THREAD

**Issue by Vifon** [lecram/rover#9]
I've just noticed that the unicode filenames are broken. `Æ` is displayed as `M-C~F`, `ö` is `M-CM-6` and so on. Would adding a proper Unicode support be difficult?

**Comment by lecram** [comment]
I want to fix this, but it might take some time. =/
If I'm not mistaken, we'll need to change all curses code to use wide-char strings and then implement UTF-8 decoding to read filesystem entries plus UTF-8 encoding to write filesystem entries.

**Comment by Vifon** [comment]
Actually I think I might have just solved it. I've linked against `libncursesw` instead of `libcurses` and it just worked. Is that ok?

**Comment by lecram** [comment]
Are you sure? It doesn't work for me. It might show Unicode characters correctly but the string lengths are computed incorrectly, leading to various bugs. Also, I can't type non-ASCII characters in the line input (e.g. while searching).

**Comment by Vifon** [comment]
You're right, there are some issues I've missed. But still it's a good start.

**Comment by lecram** [comment]
@cf17fb505480dcfaa879873f57ce4abc33d1b1e4 hopefully fixes it. More testing is welcome.

**Comment by Vifon** [comment]
Now I can type most of the Polish non-ASCII characters in the searchbar. Most but not all, for example I cannot type `ą` (<kbd>AltGr+a</kbd>).

**Comment by lecram** [comment]
My bad. Some characters were being confused with special keys (`ą` was right arrow). Can you check if it's working now?

**Comment by Vifon** [comment]
Seems to be working just fine. Thanks!
